create table if not exists departamentos (
       id integer generated by default as identity,
        descricao varchar(255) not null,
        primary key (id)
);

insert into departamentos (descricao) values 
('Financeiro'),
('Fiscal'),
('Tecnologia da Informação'),
('Suporte');


